/// Error set for Evm operations
pub const CallError = error{
    InvalidJump,
    OutOfGas,
    StackUnderflow,
    StackOverflow,
    ContractNotFound,
    PrecompileError,
    MemoryError,
    StorageError,
    CallDepthExceeded,
    InsufficientBalance,
    ContractCollision,
    InvalidBytecode,
    StaticCallViolation,
    InvalidOpcode,
    RevertExecution,
    OutOfMemory,
    AllocationError,
    AccountNotFound,
    InvalidJumpDestination,
    MissingJumpDestMetadata,
    InitcodeTooLarge,
    TruncatedPush,
    OutOfBounds,
    WriteProtection,
    BytecodeTooLarge,
    InvalidPush,
    CreateInitCodeSizeLimit,
    CreateContractSizeLimit,
    ExecutionTimeout,
    // CallParams validation errors
    GasZeroError,
    InvalidInputSize,
    InvalidInitCodeSize,
    InvalidCreateValue,
    InvalidStaticCallValue,
    // IO errors
    NoSpaceLeft,
};
