pub const SyntaxKind = enum {
    SourceFile,

    // Item-level syntax nodes
    ContractItem,
    FunctionItem,
    StructItem,
    BitfieldItem,
    EnumItem,
    TraitItem,
    ImplItem,
    TypeAliasItem,
    LogDeclItem,
    ErrorDeclItem,
    ImportItem,
    GhostItem,
    ContractInvariantItem,
    VariableItem,
    FieldItem,
    ConstantItem,

    // Statement-level syntax nodes
    IfStmt,
    WhileStmt,
    ForStmt,
    SwitchStmt,
    TryStmt,
    ReturnStmt,
    VariableDeclStmt,
    AssertStmt,
    AssumeStmt,
    HavocStmt,
    BreakStmt,
    ContinueStmt,
    AssignStmt,
    ExprStmt,
    BlockStmt,
    LogStmt,
    LockStmt,
    UnlockStmt,
    LabeledBlockStmt,
    DestructuringAssignStmt,
    CompoundAssignStmt,

    // Expression-level syntax nodes
    BinaryExpr,
    RangeExpr,
    UnaryExpr,
    CallExpr,
    FieldExpr,
    IndexExpr,
    GroupExpr,
    TupleExpr,
    ArrayLiteral,
    StructLiteral,
    SwitchExpr,
    QuantifiedExpr,
    OldExpr,
    BuiltinExpr,
    ErrorReturnExpr,
    Literal,
    NameExpr,
    TryExpr,
    ErrorExpr,
    ComptimeExpr,

    // Type-level syntax nodes
    PathType,
    GenericType,
    TupleType,
    ArrayType,
    SliceType,
    ErrorUnionType,
    AnonymousStructType,

    // Structural syntax nodes
    ParameterList,
    Parameter,
    Body,
    SwitchArm,
    SwitchExprArm,
    CatchClause,
    SpecClause,
    TraitBoundClause,
    StructField,
    TraitMethodSignature,
    EnumVariant,
    BitfieldField,
    LogField,
    InvariantClause,
    DestructuringPattern,
    DestructuringField,
    AnonymousStructField,
    AnonymousStructLiteralField,

    // Legacy delimiter-group fallback nodes kept during migration
    GroupParen,
    GroupBrace,
    GroupBracket,

    Error,
};
