#!/usr/bin/env python3
"""Generate the Lean axiom audit for the trusted Ora formal tree."""

from __future__ import annotations

import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parents[1]
FORMAL_ROOT = ROOT / "formal" / "Ora"
TRANSIENT_TEST_MODULE_DIRS = frozenset({"B6StorageFixture", "ProofCheckScratch"})

LEAN_IDENT = r"[A-Za-z_][A-Za-z0-9_'?!]*"
LEAN_DOTTED_IDENT = rf"{LEAN_IDENT}(?:\.{LEAN_IDENT})*"

NAMESPACE_RE = re.compile(rf"^\s*namespace\s+({LEAN_DOTTED_IDENT})\s*$")
END_RE = re.compile(rf"^\s*end(?:\s+({LEAN_DOTTED_IDENT}))?\s*$")
DECL_RE = re.compile(
    r"^\s*(?:@\[[^\]]+\]\s*)*(?:(private|local)\s+)?(?:protected\s+)?"
    rf"(?:theorem|lemma)\s+({LEAN_DOTTED_IDENT})\b"
)


def strip_comments(line: str, in_block_comment: bool) -> tuple[str, bool]:
    out: list[str] = []
    index = 0
    while index < len(line):
        if in_block_comment:
            end = line.find("-/", index)
            if end == -1:
                return "".join(out), True
            index = end + 2
            in_block_comment = False
            continue

        line_comment = line.find("--", index)
        block_comment = line.find("/-", index)
        if line_comment != -1 and (block_comment == -1 or line_comment < block_comment):
            out.append(line[index:line_comment])
            return "".join(out), False
        if block_comment == -1:
            out.append(line[index:])
            return "".join(out), False
        out.append(line[index:block_comment])
        index = block_comment + 2
        in_block_comment = True
    return "".join(out), in_block_comment


def qualify(namespace_stack: list[str], decl_name: str) -> str:
    if decl_name.startswith("_root_."):
        return decl_name[len("_root_.") :]
    if decl_name.startswith("Ora."):
        return decl_name
    namespace = ".".join(namespace_stack)
    if namespace:
        return f"{namespace}.{decl_name}"
    return decl_name


def discover_targets() -> list[str]:
    targets: list[str] = []
    seen: set[str] = set()
    for path in sorted(FORMAL_ROOT.rglob("*.lean")):
        relative_parts = path.relative_to(FORMAL_ROOT).parts
        if relative_parts and relative_parts[0] in TRANSIENT_TEST_MODULE_DIRS:
            continue
        namespace_stack: list[str] = []
        in_block_comment = False
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line, in_block_comment = strip_comments(raw_line, in_block_comment)
            stripped = line.strip()
            if not stripped:
                continue

            if match := NAMESPACE_RE.match(stripped):
                namespace_stack.append(match.group(1))
                continue

            if match := END_RE.match(stripped):
                name = match.group(1)
                if name is not None and namespace_stack:
                    last = namespace_stack[-1]
                    full = ".".join(namespace_stack)
                    if name == last or name == full:
                        namespace_stack.pop()
                continue

            if match := DECL_RE.match(stripped):
                if match.group(1) is not None:
                    continue
                name = qualify(namespace_stack, match.group(2))
                if name not in seen:
                    seen.add(name)
                    targets.append(name)
    return targets


def emit(targets: list[str]) -> str:
    lines: list[str] = [
        "-- Generated by scripts/check-formal-trust-surface.py",
        "import Ora",
        "import Lean",
        "import Lean.Util.CollectAxioms",
        "",
        "open Lean Elab Command",
        "",
        "namespace Ora.FormalAxiomAudit",
        "",
        "def normalizeNames (names : Array Name) : Array Name := Id.run do",
        "  let mut out := #[]",
        "  for name in names.qsort Name.lt do",
        "    unless out.any (fun existing => existing == name) do",
        "      out := out.push name",
        "  return out",
        "",
        "def allowedAxiom (name : Name) : Bool :=",
        "  name == `propext || name == `Quot.sound",
        "",
        "def auditTargets : Array Name := #[",
    ]
    for index, target in enumerate(targets):
        suffix = "," if index + 1 < len(targets) else ""
        lines.append(f"  `{target}{suffix}")
    lines.extend(
        [
            "]",
            "",
            "syntax (name := oraFormalAxiomAudit) \"#ora_formal_axiom_audit\" : command",
            "",
            "@[command_elab oraFormalAxiomAudit] def elabOraFormalAxiomAudit : CommandElab := fun _ => do",
            "  let env <- getEnv",
            "",
            "  let mut unexpected : Array (Prod Name Name) := #[]",
            "  for decl in auditTargets do",
            "    unless env.contains decl do",
            "      throwError m!\"missing audited declaration: {decl}\"",
            "",
            "    let deps <- collectAxioms decl",
            "    for dep in normalizeNames deps do",
            "      unless allowedAxiom dep do",
            "        unexpected := unexpected.push (decl, dep)",
            "",
            "  if unexpected.size != 0 then",
            "    let rendered := unexpected.map (fun pair => s!\"{pair.1} -> {pair.2}\")",
            "    let renderedText := String.intercalate \"\\n\" rendered.toList",
            "    throwError m!\"unexpected Lean axiom dependencies in Ora formal tree:\\n{renderedText}\"",
            "",
            "  logInfo m!\"OK: audited {auditTargets.size} Ora formal theorem/lemma declaration(s)\"",
            "",
            "end Ora.FormalAxiomAudit",
            "",
            "#ora_formal_axiom_audit",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    targets = discover_targets()
    if not targets:
        raise SystemExit("no Ora formal theorem/lemma declarations found")
    print(emit(targets), end="")


if __name__ == "__main__":
    main()
