//! Debug-artifact regression corpus.
//!
//! Drives `zig-out/bin/ora debug --no-tui` against each fixture under
//! tests/debug_artifacts/ and asserts byte-equality against the
//! committed golden .sourcemap.json and .debug.json files.
//!
//! Goldens are regenerated by re-running `ora debug --no-tui` against
//! each fixture and copying the emitted `*.sourcemap.json` /
//! `*.debug.json` over the matching `*.golden.json` files.
//!
//! The compiler binary is required for these tests. They skip cleanly
//! (with a logged message) when the binary is absent so a developer
//! running just the unit-tests subset isn't blocked.

const std = @import("std");
const testing = std.testing;

const ORA_BINARY_REL = "zig-out/bin/ora";
const FIXTURES_REL = "tests/debug_artifacts";

const Fixture = struct {
    name: []const u8,
    source_relpath: []const u8,
};

const FIXTURES = [_]Fixture{
    .{ .name = "simple_counter", .source_relpath = "tests/debug_artifacts/simple_counter/simple_counter.ora" },
    .{ .name = "liveness_dead_after_use", .source_relpath = "tests/debug_artifacts/liveness_dead_after_use/liveness_dead_after_use.ora" },
};

fn binaryAvailable() bool {
    std.fs.cwd().access(ORA_BINARY_REL, .{}) catch return false;
    return true;
}

/// Run `ora debug --no-tui <fixture> -o <output_dir>`.
fn runOraDebug(allocator: std.mem.Allocator, fixture: Fixture, output_dir: []const u8) !void {
    const result = try std.process.Child.run(.{
        .allocator = allocator,
        .argv = &[_][]const u8{
            ORA_BINARY_REL,
            "debug",
            "--no-tui",
            fixture.source_relpath,
            "-o",
            output_dir,
        },
        .max_output_bytes = 4 * 1024 * 1024,
    });
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);

    switch (result.term) {
        .Exited => |code| if (code != 0) {
            std.debug.print(
                "ora debug --no-tui exited with {d}\nstdout:\n{s}\nstderr:\n{s}\n",
                .{ code, result.stdout, result.stderr },
            );
            return error.OraDebugFailed;
        },
        else => {
            std.debug.print("ora debug --no-tui terminated abnormally: {}\n", .{result.term});
            return error.OraDebugFailed;
        },
    }
}

fn readFile(allocator: std.mem.Allocator, path: []const u8) ![]u8 {
    return std.fs.cwd().readFileAlloc(allocator, path, 16 * 1024 * 1024);
}

fn assertEqualOrDescribeDiff(
    allocator: std.mem.Allocator,
    fixture_name: []const u8,
    label: []const u8,
    actual_path: []const u8,
    golden_path: []const u8,
) !void {
    const actual = try readFile(allocator, actual_path);
    defer allocator.free(actual);
    const golden = try readFile(allocator, golden_path);
    defer allocator.free(golden);

    if (std.mem.eql(u8, actual, golden)) return;

    std.debug.print(
        "[{s}] {s} diverged from {s}\n" ++
            "  actual : {s} ({d} bytes)\n" ++
            "  golden : {s} ({d} bytes)\n" ++
            "If the change is intentional, regenerate goldens by running\n" ++
            "  ./zig-out/bin/ora debug --no-tui {s} -o /tmp/dbg && \\\n" ++
            "  cp /tmp/dbg/{s}.sourcemap.json tests/debug_artifacts/{s}/sourcemap.golden.json && \\\n" ++
            "  cp /tmp/dbg/{s}.debug.json     tests/debug_artifacts/{s}/debug.golden.json\n",
        .{
            fixture_name, label,      golden_path,
            actual_path,  actual.len, golden_path,
            golden.len,
                // regen instructions:
            FIXTURES[0].source_relpath, // simple_counter for now
            fixture_name,
            fixture_name,
            fixture_name,
            fixture_name,
        },
    );
    return error.GoldenMismatch;
}

test "debug-artifacts regression corpus matches goldens" {
    if (!binaryAvailable()) {
        std.debug.print(
            "skip: {s} not found — run `zig build install` first to enable debug-artifact regression tests\n",
            .{ORA_BINARY_REL},
        );
        return error.SkipZigTest;
    }

    const allocator = testing.allocator;

    for (FIXTURES) |fixture| {
        // Each fixture lands in its own temp dir so failures across fixtures
        // don't shadow each other.
        const out_dir = try std.fmt.allocPrint(
            allocator,
            "/tmp/ora_dbg_artifacts_{s}",
            .{fixture.name},
        );
        defer allocator.free(out_dir);

        std.fs.cwd().deleteTree(out_dir) catch {};
        try runOraDebug(allocator, fixture, out_dir);

        const stem = std.fs.path.stem(fixture.source_relpath);

        const actual_sourcemap = try std.fmt.allocPrint(
            allocator,
            "{s}/{s}.sourcemap.json",
            .{ out_dir, stem },
        );
        defer allocator.free(actual_sourcemap);
        const actual_debug = try std.fmt.allocPrint(
            allocator,
            "{s}/{s}.debug.json",
            .{ out_dir, stem },
        );
        defer allocator.free(actual_debug);

        const golden_sourcemap = try std.fmt.allocPrint(
            allocator,
            "{s}/{s}/sourcemap.golden.json",
            .{ FIXTURES_REL, fixture.name },
        );
        defer allocator.free(golden_sourcemap);
        const golden_debug = try std.fmt.allocPrint(
            allocator,
            "{s}/{s}/debug.golden.json",
            .{ FIXTURES_REL, fixture.name },
        );
        defer allocator.free(golden_debug);

        try assertEqualOrDescribeDiff(allocator, fixture.name, "sourcemap.json", actual_sourcemap, golden_sourcemap);
        try assertEqualOrDescribeDiff(allocator, fixture.name, "debug.json", actual_debug, golden_debug);
    }
}
