const std = @import("std");

const Allocator = std.mem.Allocator;

pub const Snapshot = struct {
    open_documents: usize = 0,
    core_builds: usize = 0,
    semantic_index_builds: usize = 0,
    occurrence_index_builds: usize = 0,
    imported_member_index_builds: usize = 0,
    call_edge_index_builds: usize = 0,
    workspace_index_builds: usize = 0,
    cold_workspace_index_builds: usize = 0,
    incoming_call_target_index_builds: usize = 0,
    workspace_discovery_runs: usize = 0,
    workspace_discovery_files_seen: usize = 0,
    workspace_discovery_files_enqueued: usize = 0,
    workspace_discovery_skipped: usize = 0,
    workspace_discovery_limit_hits: usize = 0,
    workspace_discovery_cache_hits: usize = 0,
    workspace_discovery_cache_rebuilds: usize = 0,
    workspace_discovery_max_files: usize = 0,
    diagnostic_cache_builds: usize = 0,
    diagnostic_fast_builds: usize = 0,
    diagnostic_full_builds: usize = 0,
    cache_builder_capacity_requested: usize = 0,
    cache_builder_items_built: usize = 0,
    cache_builder_unused_capacity: usize = 0,
    cache_builder_growth_events: usize = 0,
    cache_side_map_capacity_requested: usize = 0,
    cache_side_map_items_built: usize = 0,
    cache_side_map_unused_capacity: usize = 0,
    cache_side_map_growth_events: usize = 0,
    response_builder_capacity_requested: usize = 0,
    response_builder_items_built: usize = 0,
    response_builder_unused_capacity: usize = 0,
    response_builder_growth_events: usize = 0,
    response_builder_capacity_bytes: usize = 0,
    response_builder_item_bytes: usize = 0,
    response_location_capacity_bytes: usize = 0,
    response_text_edit_capacity_bytes: usize = 0,
    response_completion_item_capacity_bytes: usize = 0,
    response_semantic_token_data_capacity_bytes: usize = 0,
    response_workspace_symbol_capacity_bytes: usize = 0,
    response_call_hierarchy_capacity_bytes: usize = 0,
    response_hover_capacity_bytes: usize = 0,
    response_definition_capacity_bytes: usize = 0,
    response_document_symbol_capacity_bytes: usize = 0,
    response_document_highlight_capacity_bytes: usize = 0,
    response_inlay_hint_capacity_bytes: usize = 0,
    response_code_lens_capacity_bytes: usize = 0,
    response_formatting_edit_capacity_bytes: usize = 0,
    response_selection_range_capacity_bytes: usize = 0,
    response_folding_range_capacity_bytes: usize = 0,
    response_document_link_capacity_bytes: usize = 0,
    response_code_action_capacity_bytes: usize = 0,
    response_signature_help_capacity_bytes: usize = 0,
    response_prepare_rename_capacity_bytes: usize = 0,
    response_string_bytes: usize = 0,
    response_markdown_bytes: usize = 0,
    response_location_string_bytes: usize = 0,
    response_text_edit_string_bytes: usize = 0,
    response_completion_string_bytes: usize = 0,
    response_completion_markdown_bytes: usize = 0,
    response_hover_string_bytes: usize = 0,
    response_hover_markdown_bytes: usize = 0,
    response_definition_string_bytes: usize = 0,
    response_signature_string_bytes: usize = 0,
    response_signature_markdown_bytes: usize = 0,
    response_document_symbol_string_bytes: usize = 0,
    response_workspace_symbol_string_bytes: usize = 0,
    response_call_hierarchy_string_bytes: usize = 0,
    response_inlay_hint_string_bytes: usize = 0,
    response_code_lens_string_bytes: usize = 0,
    response_formatting_edit_string_bytes: usize = 0,
    response_document_link_string_bytes: usize = 0,
    response_code_action_string_bytes: usize = 0,
    response_prepare_rename_string_bytes: usize = 0,
    dependent_diagnostic_publish_runs: usize = 0,
    dependent_diagnostic_published_documents: usize = 0,
    dependent_diagnostic_publish_skips: usize = 0,
    diagnostic_debounce_pending: usize = 0,
    diagnostic_debounce_scheduled: usize = 0,
    diagnostic_debounce_canceled: usize = 0,
    diagnostic_debounce_flushed: usize = 0,
    diagnostic_debounce_cleared: usize = 0,
    stale_document_change_skips: usize = 0,
    edit_diagnostic_fast_publishes: usize = 0,
    edit_diagnostic_full_skips: usize = 0,
    cold_documents: usize = 0,
    cold_document_max_count: usize = 0,
    cold_document_evictions: usize = 0,
    cold_document_refresh_checks: usize = 0,
    cold_document_refreshes: usize = 0,
    cold_document_stale_removals: usize = 0,
    workspace_index_entries: usize = 0,
    workspace_index_bytes: usize = 0,
    workspace_index_max_bytes: usize = 0,
    workspace_index_evictions: usize = 0,
    open_source_bytes: usize = 0,
    cold_source_bytes: usize = 0,
    cold_source_max_bytes: usize = 0,
    open_token_count: usize = 0,
    open_token_diagnostic_count: usize = 0,
    open_symbol_count: usize = 0,
    open_occurrence_count: usize = 0,
    open_imported_member_count: usize = 0,
    open_call_edge_count: usize = 0,
    workspace_index_symbol_count: usize = 0,
    workspace_index_root_symbol_count: usize = 0,
    workspace_index_callable_symbol_count: usize = 0,
    workspace_index_import_count: usize = 0,
    workspace_index_occurrence_count: usize = 0,
    workspace_index_imported_member_count: usize = 0,
    workspace_index_call_edge_count: usize = 0,
    incoming_call_target_name_count: usize = 0,
    incoming_call_target_uri_count: usize = 0,
    workspace_index_interned_string_bytes: usize = 0,
    workspace_index_interned_string_count: usize = 0,
    workspace_index_duplicate_string_bytes_saved: usize = 0,
    workspace_index_interned_string_capacity_requested: usize = 0,
    workspace_index_interned_string_items_built: usize = 0,
    workspace_index_interned_string_unused_capacity: usize = 0,
    workspace_index_interned_string_growth_events: usize = 0,
    cold_workspace_index_entries: usize = 0,
    cold_workspace_index_bytes: usize = 0,
    cold_workspace_index_interned_string_bytes: usize = 0,
    cold_workspace_index_interned_string_count: usize = 0,
    cold_workspace_index_duplicate_string_bytes_saved: usize = 0,
    cold_workspace_index_interned_string_capacity_requested: usize = 0,
    cold_workspace_index_interned_string_items_built: usize = 0,
    cold_workspace_index_interned_string_unused_capacity: usize = 0,
    cold_workspace_index_interned_string_growth_events: usize = 0,
    document_state_bytes: usize = 0,
    line_index_bytes: usize = 0,
    token_cache_bytes: usize = 0,
    std_import_alias_bytes: usize = 0,
    import_resolution_bytes: usize = 0,
    semantic_index_bytes: usize = 0,
    occurrence_index_bytes: usize = 0,
    imported_member_index_bytes: usize = 0,
    call_edge_index_bytes: usize = 0,
    incoming_call_target_index_bytes: usize = 0,
    formatting_cache_entries: usize = 0,
    formatting_cache_bytes: usize = 0,
    diagnostic_cache_bytes: usize = 0,
    lex_builds: usize = 0,
    parse_builds: usize = 0,
    ast_lower_builds: usize = 0,
    item_index_builds: usize = 0,
    resolve_builds: usize = 0,
    const_eval_builds: usize = 0,
    type_check_builds: usize = 0,
    formatter_builds: usize = 0,
    server_allocator_alloc_calls: usize = 0,
    server_allocator_resize_calls: usize = 0,
    server_allocator_remap_calls: usize = 0,
    server_allocator_free_calls: usize = 0,
    server_allocator_bytes_allocated: usize = 0,
    server_allocator_bytes_freed: usize = 0,
    server_allocator_bytes_live: usize = 0,
    server_allocator_bytes_peak: usize = 0,
    server_allocator_unscoped_alloc_calls: usize = 0,
    server_allocator_unscoped_bytes_allocated: usize = 0,
    server_allocator_request_alloc_calls: usize = 0,
    server_allocator_request_bytes_allocated: usize = 0,
    server_allocator_response_alloc_calls: usize = 0,
    server_allocator_response_bytes_allocated: usize = 0,
    server_allocator_cache_build_alloc_calls: usize = 0,
    server_allocator_cache_build_bytes_allocated: usize = 0,
    server_allocator_temp_analysis_alloc_calls: usize = 0,
    server_allocator_temp_analysis_bytes_allocated: usize = 0,
};

pub fn build(arena: Allocator, snapshot: Snapshot) !std.json.ObjectMap {
    var object = std.json.ObjectMap.init(arena);
    try putJsonInt(&object, "openDocuments", snapshot.open_documents);
    try putJsonInt(&object, "coreBuilds", snapshot.core_builds);
    try putJsonInt(&object, "semanticIndexBuilds", snapshot.semantic_index_builds);
    try putJsonInt(&object, "occurrenceIndexBuilds", snapshot.occurrence_index_builds);
    try putJsonInt(&object, "importedMemberIndexBuilds", snapshot.imported_member_index_builds);
    try putJsonInt(&object, "callEdgeIndexBuilds", snapshot.call_edge_index_builds);
    try putJsonInt(&object, "workspaceIndexBuilds", snapshot.workspace_index_builds);
    try putJsonInt(&object, "coldWorkspaceIndexBuilds", snapshot.cold_workspace_index_builds);
    try putJsonInt(&object, "incomingCallTargetIndexBuilds", snapshot.incoming_call_target_index_builds);
    try putJsonInt(&object, "workspaceDiscoveryRuns", snapshot.workspace_discovery_runs);
    try putJsonInt(&object, "workspaceDiscoveryFilesSeen", snapshot.workspace_discovery_files_seen);
    try putJsonInt(&object, "workspaceDiscoveryFilesEnqueued", snapshot.workspace_discovery_files_enqueued);
    try putJsonInt(&object, "workspaceDiscoverySkipped", snapshot.workspace_discovery_skipped);
    try putJsonInt(&object, "workspaceDiscoveryLimitHits", snapshot.workspace_discovery_limit_hits);
    try putJsonInt(&object, "workspaceDiscoveryCacheHits", snapshot.workspace_discovery_cache_hits);
    try putJsonInt(&object, "workspaceDiscoveryCacheRebuilds", snapshot.workspace_discovery_cache_rebuilds);
    try putJsonInt(&object, "workspaceDiscoveryMaxFiles", snapshot.workspace_discovery_max_files);
    try putJsonInt(&object, "diagnosticCacheBuilds", snapshot.diagnostic_cache_builds);
    try putJsonInt(&object, "diagnosticFastBuilds", snapshot.diagnostic_fast_builds);
    try putJsonInt(&object, "diagnosticFullBuilds", snapshot.diagnostic_full_builds);
    try putJsonInt(&object, "cacheBuilderCapacityRequested", snapshot.cache_builder_capacity_requested);
    try putJsonInt(&object, "cacheBuilderItemsBuilt", snapshot.cache_builder_items_built);
    try putJsonInt(&object, "cacheBuilderUnusedCapacity", snapshot.cache_builder_unused_capacity);
    try putJsonInt(&object, "cacheBuilderGrowthEvents", snapshot.cache_builder_growth_events);
    try putJsonInt(&object, "cacheSideMapCapacityRequested", snapshot.cache_side_map_capacity_requested);
    try putJsonInt(&object, "cacheSideMapItemsBuilt", snapshot.cache_side_map_items_built);
    try putJsonInt(&object, "cacheSideMapUnusedCapacity", snapshot.cache_side_map_unused_capacity);
    try putJsonInt(&object, "cacheSideMapGrowthEvents", snapshot.cache_side_map_growth_events);
    try putJsonInt(&object, "responseBuilderCapacityRequested", snapshot.response_builder_capacity_requested);
    try putJsonInt(&object, "responseBuilderItemsBuilt", snapshot.response_builder_items_built);
    try putJsonInt(&object, "responseBuilderUnusedCapacity", snapshot.response_builder_unused_capacity);
    try putJsonInt(&object, "responseBuilderGrowthEvents", snapshot.response_builder_growth_events);
    try putJsonInt(&object, "responseBuilderCapacityBytes", snapshot.response_builder_capacity_bytes);
    try putJsonInt(&object, "responseBuilderItemBytes", snapshot.response_builder_item_bytes);
    try putJsonInt(&object, "responseLocationCapacityBytes", snapshot.response_location_capacity_bytes);
    try putJsonInt(&object, "responseTextEditCapacityBytes", snapshot.response_text_edit_capacity_bytes);
    try putJsonInt(&object, "responseCompletionItemCapacityBytes", snapshot.response_completion_item_capacity_bytes);
    try putJsonInt(&object, "responseSemanticTokenDataCapacityBytes", snapshot.response_semantic_token_data_capacity_bytes);
    try putJsonInt(&object, "responseWorkspaceSymbolCapacityBytes", snapshot.response_workspace_symbol_capacity_bytes);
    try putJsonInt(&object, "responseCallHierarchyCapacityBytes", snapshot.response_call_hierarchy_capacity_bytes);
    try putJsonInt(&object, "responseHoverCapacityBytes", snapshot.response_hover_capacity_bytes);
    try putJsonInt(&object, "responseDefinitionCapacityBytes", snapshot.response_definition_capacity_bytes);
    try putJsonInt(&object, "responseDocumentSymbolCapacityBytes", snapshot.response_document_symbol_capacity_bytes);
    try putJsonInt(&object, "responseDocumentHighlightCapacityBytes", snapshot.response_document_highlight_capacity_bytes);
    try putJsonInt(&object, "responseInlayHintCapacityBytes", snapshot.response_inlay_hint_capacity_bytes);
    try putJsonInt(&object, "responseCodeLensCapacityBytes", snapshot.response_code_lens_capacity_bytes);
    try putJsonInt(&object, "responseFormattingEditCapacityBytes", snapshot.response_formatting_edit_capacity_bytes);
    try putJsonInt(&object, "responseSelectionRangeCapacityBytes", snapshot.response_selection_range_capacity_bytes);
    try putJsonInt(&object, "responseFoldingRangeCapacityBytes", snapshot.response_folding_range_capacity_bytes);
    try putJsonInt(&object, "responseDocumentLinkCapacityBytes", snapshot.response_document_link_capacity_bytes);
    try putJsonInt(&object, "responseCodeActionCapacityBytes", snapshot.response_code_action_capacity_bytes);
    try putJsonInt(&object, "responseSignatureHelpCapacityBytes", snapshot.response_signature_help_capacity_bytes);
    try putJsonInt(&object, "responsePrepareRenameCapacityBytes", snapshot.response_prepare_rename_capacity_bytes);
    try putJsonInt(&object, "responseStringBytes", snapshot.response_string_bytes);
    try putJsonInt(&object, "responseMarkdownBytes", snapshot.response_markdown_bytes);
    try putJsonInt(&object, "responseLocationStringBytes", snapshot.response_location_string_bytes);
    try putJsonInt(&object, "responseTextEditStringBytes", snapshot.response_text_edit_string_bytes);
    try putJsonInt(&object, "responseCompletionStringBytes", snapshot.response_completion_string_bytes);
    try putJsonInt(&object, "responseCompletionMarkdownBytes", snapshot.response_completion_markdown_bytes);
    try putJsonInt(&object, "responseHoverStringBytes", snapshot.response_hover_string_bytes);
    try putJsonInt(&object, "responseHoverMarkdownBytes", snapshot.response_hover_markdown_bytes);
    try putJsonInt(&object, "responseDefinitionStringBytes", snapshot.response_definition_string_bytes);
    try putJsonInt(&object, "responseSignatureStringBytes", snapshot.response_signature_string_bytes);
    try putJsonInt(&object, "responseSignatureMarkdownBytes", snapshot.response_signature_markdown_bytes);
    try putJsonInt(&object, "responseDocumentSymbolStringBytes", snapshot.response_document_symbol_string_bytes);
    try putJsonInt(&object, "responseWorkspaceSymbolStringBytes", snapshot.response_workspace_symbol_string_bytes);
    try putJsonInt(&object, "responseCallHierarchyStringBytes", snapshot.response_call_hierarchy_string_bytes);
    try putJsonInt(&object, "responseInlayHintStringBytes", snapshot.response_inlay_hint_string_bytes);
    try putJsonInt(&object, "responseCodeLensStringBytes", snapshot.response_code_lens_string_bytes);
    try putJsonInt(&object, "responseFormattingEditStringBytes", snapshot.response_formatting_edit_string_bytes);
    try putJsonInt(&object, "responseDocumentLinkStringBytes", snapshot.response_document_link_string_bytes);
    try putJsonInt(&object, "responseCodeActionStringBytes", snapshot.response_code_action_string_bytes);
    try putJsonInt(&object, "responsePrepareRenameStringBytes", snapshot.response_prepare_rename_string_bytes);
    try putJsonInt(&object, "dependentDiagnosticPublishRuns", snapshot.dependent_diagnostic_publish_runs);
    try putJsonInt(&object, "dependentDiagnosticPublishedDocuments", snapshot.dependent_diagnostic_published_documents);
    try putJsonInt(&object, "dependentDiagnosticPublishSkips", snapshot.dependent_diagnostic_publish_skips);
    try putJsonInt(&object, "diagnosticDebouncePending", snapshot.diagnostic_debounce_pending);
    try putJsonInt(&object, "diagnosticDebounceScheduled", snapshot.diagnostic_debounce_scheduled);
    try putJsonInt(&object, "diagnosticDebounceCanceled", snapshot.diagnostic_debounce_canceled);
    try putJsonInt(&object, "diagnosticDebounceFlushed", snapshot.diagnostic_debounce_flushed);
    try putJsonInt(&object, "diagnosticDebounceCleared", snapshot.diagnostic_debounce_cleared);
    try putJsonInt(&object, "staleDocumentChangeSkips", snapshot.stale_document_change_skips);
    try putJsonInt(&object, "editDiagnosticFastPublishes", snapshot.edit_diagnostic_fast_publishes);
    try putJsonInt(&object, "editDiagnosticFullSkips", snapshot.edit_diagnostic_full_skips);
    try putJsonInt(&object, "coldDocuments", snapshot.cold_documents);
    try putJsonInt(&object, "coldDocumentMaxCount", snapshot.cold_document_max_count);
    try putJsonInt(&object, "coldDocumentEvictions", snapshot.cold_document_evictions);
    try putJsonInt(&object, "coldDocumentRefreshChecks", snapshot.cold_document_refresh_checks);
    try putJsonInt(&object, "coldDocumentRefreshes", snapshot.cold_document_refreshes);
    try putJsonInt(&object, "coldDocumentStaleRemovals", snapshot.cold_document_stale_removals);
    try putJsonInt(&object, "workspaceIndexEntries", snapshot.workspace_index_entries);
    try putJsonInt(&object, "workspaceIndexBytes", snapshot.workspace_index_bytes);
    try putJsonInt(&object, "workspaceIndexMaxBytes", snapshot.workspace_index_max_bytes);
    try putJsonInt(&object, "workspaceIndexEvictions", snapshot.workspace_index_evictions);
    try putJsonInt(&object, "openSourceBytes", snapshot.open_source_bytes);
    try putJsonInt(&object, "coldSourceBytes", snapshot.cold_source_bytes);
    try putJsonInt(&object, "coldSourceMaxBytes", snapshot.cold_source_max_bytes);
    try putJsonInt(&object, "openTokenCount", snapshot.open_token_count);
    try putJsonInt(&object, "openTokenDiagnosticCount", snapshot.open_token_diagnostic_count);
    try putJsonInt(&object, "openSymbolCount", snapshot.open_symbol_count);
    try putJsonInt(&object, "openOccurrenceCount", snapshot.open_occurrence_count);
    try putJsonInt(&object, "openImportedMemberCount", snapshot.open_imported_member_count);
    try putJsonInt(&object, "openCallEdgeCount", snapshot.open_call_edge_count);
    try putJsonInt(&object, "workspaceIndexSymbolCount", snapshot.workspace_index_symbol_count);
    try putJsonInt(&object, "workspaceIndexRootSymbolCount", snapshot.workspace_index_root_symbol_count);
    try putJsonInt(&object, "workspaceIndexCallableSymbolCount", snapshot.workspace_index_callable_symbol_count);
    try putJsonInt(&object, "workspaceIndexImportCount", snapshot.workspace_index_import_count);
    try putJsonInt(&object, "workspaceIndexOccurrenceCount", snapshot.workspace_index_occurrence_count);
    try putJsonInt(&object, "workspaceIndexImportedMemberCount", snapshot.workspace_index_imported_member_count);
    try putJsonInt(&object, "workspaceIndexCallEdgeCount", snapshot.workspace_index_call_edge_count);
    try putJsonInt(&object, "incomingCallTargetNameCount", snapshot.incoming_call_target_name_count);
    try putJsonInt(&object, "incomingCallTargetUriCount", snapshot.incoming_call_target_uri_count);
    try putJsonInt(&object, "workspaceIndexInternedStringBytes", snapshot.workspace_index_interned_string_bytes);
    try putJsonInt(&object, "workspaceIndexInternedStringCount", snapshot.workspace_index_interned_string_count);
    try putJsonInt(&object, "workspaceIndexDuplicateStringBytesSaved", snapshot.workspace_index_duplicate_string_bytes_saved);
    try putJsonInt(&object, "workspaceIndexInternedStringCapacityRequested", snapshot.workspace_index_interned_string_capacity_requested);
    try putJsonInt(&object, "workspaceIndexInternedStringItemsBuilt", snapshot.workspace_index_interned_string_items_built);
    try putJsonInt(&object, "workspaceIndexInternedStringUnusedCapacity", snapshot.workspace_index_interned_string_unused_capacity);
    try putJsonInt(&object, "workspaceIndexInternedStringGrowthEvents", snapshot.workspace_index_interned_string_growth_events);
    try putJsonInt(&object, "coldWorkspaceIndexEntries", snapshot.cold_workspace_index_entries);
    try putJsonInt(&object, "coldWorkspaceIndexBytes", snapshot.cold_workspace_index_bytes);
    try putJsonInt(&object, "coldWorkspaceIndexInternedStringBytes", snapshot.cold_workspace_index_interned_string_bytes);
    try putJsonInt(&object, "coldWorkspaceIndexInternedStringCount", snapshot.cold_workspace_index_interned_string_count);
    try putJsonInt(&object, "coldWorkspaceIndexDuplicateStringBytesSaved", snapshot.cold_workspace_index_duplicate_string_bytes_saved);
    try putJsonInt(&object, "coldWorkspaceIndexInternedStringCapacityRequested", snapshot.cold_workspace_index_interned_string_capacity_requested);
    try putJsonInt(&object, "coldWorkspaceIndexInternedStringItemsBuilt", snapshot.cold_workspace_index_interned_string_items_built);
    try putJsonInt(&object, "coldWorkspaceIndexInternedStringUnusedCapacity", snapshot.cold_workspace_index_interned_string_unused_capacity);
    try putJsonInt(&object, "coldWorkspaceIndexInternedStringGrowthEvents", snapshot.cold_workspace_index_interned_string_growth_events);
    try putJsonInt(&object, "documentStateBytes", snapshot.document_state_bytes);
    try putJsonInt(&object, "lineIndexBytes", snapshot.line_index_bytes);
    try putJsonInt(&object, "tokenCacheBytes", snapshot.token_cache_bytes);
    try putJsonInt(&object, "stdImportAliasBytes", snapshot.std_import_alias_bytes);
    try putJsonInt(&object, "importResolutionBytes", snapshot.import_resolution_bytes);
    try putJsonInt(&object, "semanticIndexBytes", snapshot.semantic_index_bytes);
    try putJsonInt(&object, "occurrenceIndexBytes", snapshot.occurrence_index_bytes);
    try putJsonInt(&object, "importedMemberIndexBytes", snapshot.imported_member_index_bytes);
    try putJsonInt(&object, "callEdgeIndexBytes", snapshot.call_edge_index_bytes);
    try putJsonInt(&object, "incomingCallTargetIndexBytes", snapshot.incoming_call_target_index_bytes);
    try putJsonInt(&object, "formattingCacheEntries", snapshot.formatting_cache_entries);
    try putJsonInt(&object, "formattingCacheBytes", snapshot.formatting_cache_bytes);
    try putJsonInt(&object, "diagnosticCacheBytes", snapshot.diagnostic_cache_bytes);
    try putJsonInt(&object, "lexBuilds", snapshot.lex_builds);
    try putJsonInt(&object, "parseBuilds", snapshot.parse_builds);
    try putJsonInt(&object, "astLowerBuilds", snapshot.ast_lower_builds);
    try putJsonInt(&object, "itemIndexBuilds", snapshot.item_index_builds);
    try putJsonInt(&object, "resolveBuilds", snapshot.resolve_builds);
    try putJsonInt(&object, "constEvalBuilds", snapshot.const_eval_builds);
    try putJsonInt(&object, "typeCheckBuilds", snapshot.type_check_builds);
    try putJsonInt(&object, "formatterBuilds", snapshot.formatter_builds);
    try putJsonInt(&object, "serverAllocatorAllocCalls", snapshot.server_allocator_alloc_calls);
    try putJsonInt(&object, "serverAllocatorResizeCalls", snapshot.server_allocator_resize_calls);
    try putJsonInt(&object, "serverAllocatorRemapCalls", snapshot.server_allocator_remap_calls);
    try putJsonInt(&object, "serverAllocatorFreeCalls", snapshot.server_allocator_free_calls);
    try putJsonInt(&object, "serverAllocatorBytesAllocated", snapshot.server_allocator_bytes_allocated);
    try putJsonInt(&object, "serverAllocatorBytesFreed", snapshot.server_allocator_bytes_freed);
    try putJsonInt(&object, "serverAllocatorBytesLive", snapshot.server_allocator_bytes_live);
    try putJsonInt(&object, "serverAllocatorBytesPeak", snapshot.server_allocator_bytes_peak);
    try putJsonInt(&object, "serverAllocatorUnscopedAllocCalls", snapshot.server_allocator_unscoped_alloc_calls);
    try putJsonInt(&object, "serverAllocatorUnscopedBytesAllocated", snapshot.server_allocator_unscoped_bytes_allocated);
    try putJsonInt(&object, "serverAllocatorRequestAllocCalls", snapshot.server_allocator_request_alloc_calls);
    try putJsonInt(&object, "serverAllocatorRequestBytesAllocated", snapshot.server_allocator_request_bytes_allocated);
    try putJsonInt(&object, "serverAllocatorResponseAllocCalls", snapshot.server_allocator_response_alloc_calls);
    try putJsonInt(&object, "serverAllocatorResponseBytesAllocated", snapshot.server_allocator_response_bytes_allocated);
    try putJsonInt(&object, "serverAllocatorCacheBuildAllocCalls", snapshot.server_allocator_cache_build_alloc_calls);
    try putJsonInt(&object, "serverAllocatorCacheBuildBytesAllocated", snapshot.server_allocator_cache_build_bytes_allocated);
    try putJsonInt(&object, "serverAllocatorTempAnalysisAllocCalls", snapshot.server_allocator_temp_analysis_alloc_calls);
    try putJsonInt(&object, "serverAllocatorTempAnalysisBytesAllocated", snapshot.server_allocator_temp_analysis_bytes_allocated);
    return object;
}

fn putJsonInt(object: *std.json.ObjectMap, key: []const u8, value: usize) !void {
    const integer_value: i64 = if (value > std.math.maxInt(i64)) std.math.maxInt(i64) else @intCast(value);
    try object.put(key, .{ .integer = integer_value });
}
