const ora_root = @import("ora_root");

const allocation_stats = ora_root.lsp.allocation_stats;
const phase_stats = ora_root.lsp.phase_stats;

const cache_stats_response = @import("cache_stats_response.zig");

pub const RuntimeCounters = struct {
    dependent_diagnostic_publish_runs: usize = 0,
    dependent_diagnostic_published_documents: usize = 0,
    dependent_diagnostic_publish_skips: usize = 0,
    stale_document_change_skips: usize = 0,
    edit_diagnostic_fast_publishes: usize = 0,
    edit_diagnostic_full_skips: usize = 0,
};

pub const AllocationSnapshot = struct {
    totals: ?*const allocation_stats.Stats = null,
    unscoped: allocation_stats.ScopedStats = .{},
    request: allocation_stats.ScopedStats = .{},
    response: allocation_stats.ScopedStats = .{},
    cache_build: allocation_stats.ScopedStats = .{},
    temp_analysis: allocation_stats.ScopedStats = .{},
};

pub fn build(
    docs: anytype,
    workspace_discovery: anytype,
    diagnostics: anytype,
    response_counters: anytype,
    phase_counters: phase_stats.Stats,
    runtime: RuntimeCounters,
    allocations: AllocationSnapshot,
) cache_stats_response.Snapshot {
    var snapshot: cache_stats_response.Snapshot = .{
        .open_documents = docs.openDocumentCount(),
        .open_source_bytes = docs.openSourceBytes(),
        .document_state_bytes = docs.documentStateBytes(),
        .line_index_bytes = docs.lineIndexBytes(),
        .formatting_cache_entries = docs.formattingCacheEntries(),
        .formatting_cache_bytes = docs.formattingCacheBytes(),
        .cache_builder_capacity_requested = docs.cacheBuilderCapacityRequested(),
        .cache_builder_items_built = docs.cacheBuilderItemsBuilt(),
        .cache_builder_unused_capacity = docs.cacheBuilderUnusedCapacity(),
        .cache_builder_growth_events = docs.cacheBuilderGrowthEvents(),
        .cache_side_map_capacity_requested = docs.cacheSideMapCapacityRequested(),
        .cache_side_map_items_built = docs.cacheSideMapItemsBuilt(),
        .cache_side_map_unused_capacity = docs.cacheSideMapUnusedCapacity(),
        .cache_side_map_growth_events = docs.cacheSideMapGrowthEvents(),
        .dependent_diagnostic_publish_runs = runtime.dependent_diagnostic_publish_runs,
        .dependent_diagnostic_published_documents = runtime.dependent_diagnostic_published_documents,
        .dependent_diagnostic_publish_skips = runtime.dependent_diagnostic_publish_skips,
        .diagnostic_debounce_pending = diagnostics.pendingCount(),
        .diagnostic_debounce_scheduled = diagnostics.scheduled,
        .diagnostic_debounce_canceled = diagnostics.canceled,
        .diagnostic_debounce_flushed = diagnostics.flushed,
        .diagnostic_debounce_cleared = diagnostics.cleared,
        .stale_document_change_skips = runtime.stale_document_change_skips,
        .edit_diagnostic_fast_publishes = runtime.edit_diagnostic_fast_publishes,
        .edit_diagnostic_full_skips = runtime.edit_diagnostic_full_skips,
        .workspace_index_builds = docs.workspace_index_builds,
        .cold_workspace_index_builds = docs.cold_workspace_index_builds,
        .incoming_call_target_index_builds = docs.incoming_call_target_index_builds,
        .workspace_discovery_runs = workspace_discovery.stats.runs,
        .workspace_discovery_files_seen = workspace_discovery.stats.files_seen,
        .workspace_discovery_files_enqueued = workspace_discovery.stats.files_enqueued,
        .workspace_discovery_skipped = workspace_discovery.stats.skipped,
        .workspace_discovery_limit_hits = workspace_discovery.stats.limit_hits,
        .workspace_discovery_cache_hits = workspace_discovery.stats.cache_hits,
        .workspace_discovery_cache_rebuilds = workspace_discovery.stats.cache_rebuilds,
        .workspace_discovery_max_files = workspace_discovery.max_files,
        .diagnostic_cache_builds = docs.diagnostic_cache_builds,
        .diagnostic_fast_builds = docs.diagnostic_fast_builds,
        .diagnostic_full_builds = docs.diagnostic_full_builds,
        .workspace_index_entries = docs.workspaceIndexEntries(),
        .workspace_index_bytes = docs.workspaceIndexBytes(),
        .workspace_index_max_bytes = docs.workspaceIndexMaxBytes(),
        .workspace_index_evictions = docs.workspaceIndexEvictions(),
        .workspace_index_symbol_count = docs.workspaceIndexSymbolCount(),
        .workspace_index_root_symbol_count = docs.workspaceIndexRootSymbolCount(),
        .workspace_index_callable_symbol_count = docs.workspaceIndexCallableSymbolCount(),
        .workspace_index_import_count = docs.workspaceIndexImportCount(),
        .workspace_index_occurrence_count = docs.workspaceIndexOccurrenceCount(),
        .workspace_index_imported_member_count = docs.workspaceIndexImportedMemberCount(),
        .workspace_index_call_edge_count = docs.workspaceIndexCallEdgeCount(),
        .incoming_call_target_name_count = docs.incomingCallTargetNameCount(),
        .incoming_call_target_uri_count = docs.incomingCallTargetUriCount(),
        .workspace_index_interned_string_bytes = docs.workspaceIndexInternedStringBytes(),
        .workspace_index_interned_string_count = docs.workspaceIndexInternedStringCount(),
        .workspace_index_duplicate_string_bytes_saved = docs.workspaceIndexDuplicateStringBytesSaved(),
        .workspace_index_interned_string_capacity_requested = docs.workspaceIndexInternedStringCapacityRequested(),
        .workspace_index_interned_string_items_built = docs.workspaceIndexInternedStringItemsBuilt(),
        .workspace_index_interned_string_unused_capacity = docs.workspaceIndexInternedStringUnusedCapacity(),
        .workspace_index_interned_string_growth_events = docs.workspaceIndexInternedStringGrowthEvents(),
        .cold_workspace_index_entries = docs.coldWorkspaceIndexEntries(),
        .cold_workspace_index_bytes = docs.coldWorkspaceIndexBytes(),
        .cold_workspace_index_interned_string_bytes = docs.coldWorkspaceIndexInternedStringBytes(),
        .cold_workspace_index_interned_string_count = docs.coldWorkspaceIndexInternedStringCount(),
        .cold_workspace_index_duplicate_string_bytes_saved = docs.coldWorkspaceIndexDuplicateStringBytesSaved(),
        .cold_workspace_index_interned_string_capacity_requested = docs.coldWorkspaceIndexInternedStringCapacityRequested(),
        .cold_workspace_index_interned_string_items_built = docs.coldWorkspaceIndexInternedStringItemsBuilt(),
        .cold_workspace_index_interned_string_unused_capacity = docs.coldWorkspaceIndexInternedStringUnusedCapacity(),
        .cold_workspace_index_interned_string_growth_events = docs.coldWorkspaceIndexInternedStringGrowthEvents(),
        .occurrence_index_builds = docs.occurrence_index_builds,
        .open_occurrence_count = docs.occurrenceCount(),
        .occurrence_index_bytes = docs.occurrenceIndexBytes(),
        .imported_member_index_builds = docs.imported_member_index_builds,
        .open_imported_member_count = docs.importedMemberCount(),
        .imported_member_index_bytes = docs.importedMemberIndexBytes(),
        .semantic_index_builds = docs.semantic_index_builds,
        .open_symbol_count = docs.symbolCount(),
        .semantic_index_bytes = docs.semanticIndexBytes(),
        .call_edge_index_builds = docs.call_edge_index_builds,
        .open_call_edge_count = docs.callEdgeCount(),
        .call_edge_index_bytes = docs.callEdgeIndexBytes(),
        .incoming_call_target_index_bytes = docs.incomingCallTargetIndexBytes(),
        .cold_documents = docs.coldDocumentCount(),
        .cold_document_max_count = docs.coldDocumentMaxCount(),
        .cold_document_evictions = docs.coldDocumentEvictions(),
        .cold_document_refresh_checks = docs.coldDocumentRefreshChecks(),
        .cold_document_refreshes = docs.coldDocumentRefreshes(),
        .cold_document_stale_removals = docs.coldDocumentStaleRemovals(),
        .cold_source_bytes = docs.coldSourceBytes(),
        .cold_source_max_bytes = docs.coldSourceMaxBytes(),
        .open_token_count = docs.tokenCount(),
        .open_token_diagnostic_count = docs.tokenDiagnosticCount(),
        .token_cache_bytes = docs.tokenCacheBytes(),
        .import_resolution_bytes = docs.importResolutionBytes(),
        .diagnostic_cache_bytes = docs.diagnosticCacheBytes(),
        .lex_builds = phase_counters.lex_builds,
        .parse_builds = phase_counters.parse_builds,
        .ast_lower_builds = phase_counters.ast_lower_builds,
        .item_index_builds = phase_counters.item_index_builds,
        .resolve_builds = phase_counters.resolve_builds,
        .const_eval_builds = phase_counters.const_eval_builds,
        .type_check_builds = phase_counters.type_check_builds,
        .formatter_builds = phase_counters.formatter_builds,
        .server_allocator_alloc_calls = if (allocations.totals) |stats| stats.alloc_calls else 0,
        .server_allocator_resize_calls = if (allocations.totals) |stats| stats.resize_calls else 0,
        .server_allocator_remap_calls = if (allocations.totals) |stats| stats.remap_calls else 0,
        .server_allocator_free_calls = if (allocations.totals) |stats| stats.free_calls else 0,
        .server_allocator_bytes_allocated = if (allocations.totals) |stats| stats.bytes_allocated else 0,
        .server_allocator_bytes_freed = if (allocations.totals) |stats| stats.bytes_freed else 0,
        .server_allocator_bytes_live = if (allocations.totals) |stats| stats.bytes_live else 0,
        .server_allocator_bytes_peak = if (allocations.totals) |stats| stats.bytes_peak else 0,
        .server_allocator_unscoped_alloc_calls = allocations.unscoped.alloc_calls,
        .server_allocator_unscoped_bytes_allocated = allocations.unscoped.bytes_allocated,
        .server_allocator_request_alloc_calls = allocations.request.alloc_calls,
        .server_allocator_request_bytes_allocated = allocations.request.bytes_allocated,
        .server_allocator_response_alloc_calls = allocations.response.alloc_calls,
        .server_allocator_response_bytes_allocated = allocations.response.bytes_allocated,
        .server_allocator_cache_build_alloc_calls = allocations.cache_build.alloc_calls,
        .server_allocator_cache_build_bytes_allocated = allocations.cache_build.bytes_allocated,
        .server_allocator_temp_analysis_alloc_calls = allocations.temp_analysis.alloc_calls,
        .server_allocator_temp_analysis_bytes_allocated = allocations.temp_analysis.bytes_allocated,
    };
    response_counters.writeSnapshot(&snapshot);
    return snapshot;
}
